name: 'Microsoft C++ Code Analysis Action'
description: 'Run Microsoft C++ Code Analysis to produce SARIF files for use in github/codeql-action/upload-sarif@v1'
inputs:
  cmakeBuildDirectory:
    description: 'The CMake build directory that should already be generated.'
    default: 'General'
  resultsDirectory:
    description: 'The directory in which the individual SARIF files produced by analysis will be located.'
    default: '${{ github.workspace }}/results'
  ruleset:
    description: 'Ruleset file used to determine what checks are run.'
    default: 'NativeRecommendedRules.ruleset'
  ignoreSystemHeaders:
    description: 'Uses /external arguments to ignore warnings from any headers marked as SYSTEM in CMake.'
    default: 'True'
  cleanSarif:
    description: 'SARIF files will under `results` directory are considered stale and will be deleted.'
    default: 'True'
  args:
    description: 'Optional parameters to pass to every instance of the compiler.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'