name: 'run-tests'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * SUN'

env:
  sample: '${{ github.workspace }}/test/sample'
  build: '${{ github.workspace }}/test/sample/build'
  results: '${{ github.workspace }}/test/sample/results'

jobs:
  build_and_test:
    name: build and unit tests
    runs-on: windows-latest

    steps:
    - name: Checkout action
      uses: actions/checkout@v2.3.4

    - name: Setup Node.js
      uses: actions/setup-node@v2.4.0
      with:
        node-version: '12.x'
    - name: Build
      run: npm install
    - name: Test
      run: npm test

  functional_test:
    name: run functional tests
    runs-on: windows-latest

    steps:
    - name: Checkout action
      uses: actions/checkout@v2.3.4

    - name: Initialize sample CMake Project
      uses: lukka/run-cmake@v3
      with:
        cmakeListsTxtPath: ${{ env.sample }}/CMakeLists.txt
        buildDirectory: ${{ env.build }}
        cmakeGenerator: VS16Win64
        buildWithCMake: false
      
    - name: Run action
      uses: ./
      with:
        cmakeBuildDirectory: ${{ env.build }}
        resultsDirectory: ${{ env.results }}
        ignoreSystemHeaders: true

    # TODO: remove as this as results in sample will not change between PRs
    - name: Upload SARIF results
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: ${{ env.results }}

    # TODO: Validate SARIF produced